spring:
  application:
    name: catalog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false